apiVersion: v1
kind: Service
metadata:
  labels:
    app: eureka-service-2
  name: bootu-eureka-2
spec:
  ports:
  - port: 8862
    protocol: TCP
    targetPort: 8862
    nodePort: 30862
  selector:
    app: eureka-service-2
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: eureka-service-2-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-service-2
    spec:
      containers:
      - name: bootu-eureka-2
        image: orionhank/bootu-eureka-server:latest
        ports:
        - containerPort: 8862
        env:
        - name: spring.profiles.active
          value: "peer2"

