server:
  port: 8861
spring:
  profiles: peer1
  application:
    name: bootu-eureka
eureka:
  instance:
    hostname: peer1
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  client:
    serviceUrl:
      defaultZone: http://bootu-eureka-2:8862/eureka/